### ISSUE TITLE
HU13 - Como usuario, dados dos lugares de interés (estén dados de alta o no) y un método de movilidad, quiero obtener una ruta (trayecto, distancia y duración) entre ambos lugares para visualizarla.

### ISSUE THREAD

**Issue by Mehdi1017** [gargalloeric/routify#3]
## Escenarios a implementar:

**E01 - Válido**
**Given:** La api externa está disponible.
**When:** se quiere obtener una ruta entre los lugares “Castellón” y “Valencia” con un coche.
**Then:** se muestra la ruta entre los 2 lugares.

**E02 - Inválido**
**Given:** La api externa está disponible.
**When:** se quiere obtener una ruta entre los lugares “Castellón” y “jldhkjha” con un coche.
**Then:** se lanza la excepción  PlaceNameNotValidException.

## Progreso
- [x] E01
   - [x] Test + skel
   - [x] implementación
   - [x] Refactor
- [x] E02
   - [x] Test + skel
   - [x] implementación
   - [x] Refactor

**Comment by gargalloeric** [comment]
@Mehdi1017  y @elbence en los test cuando intentas usar `toThrowError` en un test marcado como `async`, debes acompañar a `expect` de `await` y `rejects` de la siguiente manera:

```javascript
function getAsyncFruitStock() {
  return Promise.reject(new Error('empty'))
}

test('throws on pineapples', async () => {
  await expect(() => getAsyncFruitStock()).rejects.toThrowError('empty')
})
```
