### ISSUE TITLE
HU09 - Como usuario quiero poder dar de alta un vehículo para poder emplearlo como método de transporte en mis rutas.

### ISSUE THREAD

**Issue by elbence** [gargalloeric/routify#6]
**E01 - Válido**
Given: el usuario está logueado 
And: hay conexión con la bbdd
And:  no hay ningún vehículo con los datos {“matricula”: “1212XLX”, “nombre”: “nave galáctica”, “tipo-motor”: “combustión”, “consumo-100-km”: “5”} almacenado. 
When: se intenta almacenar un vehículo con los datos matricula ‘1212XLX’, nombre ‘nave galáctica’, tipo de motor ‘combustión’ y consumo a los 100 kilómetros ‘5’.
Then: se crea y se almacena el vehículo {“matricula”: “1212XLX”, “nombre”: “nave galáctica”, “tipo-motor”: “combustión”, “consumo-100-km”: “5”}

**E03 - Inválido**
Given: el usuario está logueado 
And: hay conexión con la bbdd
And:  hay ya un vehículo con los datos {“matricula”: “1313XLX”, “nombre”: “nave galáctica 2”, “tipo-motor”: “combustión”, “consumo-100-km”: “5”} almacenado. 
When: se intenta almacenar un vehículo ya almacenado con los datos matricula ‘1313XLX’,  nombre ‘nave galáctica’, tipo de motor ‘combustión’ y consumo a los 100 kilómetros ‘5’.
Then: se lanza la excepción VehicleAlreadyStoredException.

## Progreso

- [x] **E01**
    - [x] Test de aceptación
    - [x] Implementación
    - [x] Refactor
    - [x] Test de intergración
- [x] **E03**
    - [x] Test de aceptación
    - [x] Implementación
    - [x] Refactor
    - [x] Test de intergración

**Comment by gargalloeric** [comment]
@elbence y @Mehdi1017 a lo mejor deberíamos crear una clase para los vehículos donde se almacenen sus atributos, del mismo modo que hicimos con las rutas no?
